### ISSUE TITLE
It doesn't work??

### ISSUE THREAD

**Issue by GrapeAppleFruit** [Minehut/MinehutBOT#157]
So I was banned from the minehut server and it said I was banned, but I can't join back after unbanning myself from my own server? Can you help with this?

**Comment by GrapeAppleFruit** [comment]
I'm not sure if it's because I burnt a pizza orrrr. But I need this fixed urgently because I don't know why my dog's acting this way, it's been 5 days. My computer doesn't seem to be ice. Can you please help!

**Comment by Sniped** [comment]
you forgot to smear apple sauce on the burnt pizza

**Comment by jellz** [comment]
> I'm not sure if it's because I burnt a pizza orrrr. But I need this fixed urgently because I don't know why my dog's acting this way, it's been 5 days. My computer doesn't seem to be ice. Can you please help!

This happened to me too

**Comment by GrapeAppleFruit** [comment]
> you forgot to smear apple sauce on the burnt pizza

Let me try. I'll get back to you.

**Comment by GrapeAppleFruit** [comment]
It works now

**Comment by GrapeAppleFruit** [comment]
Im getting the same issue now, but now my can of dog teeth is grass???
