### ISSUE TITLE
Outdated install instructions?

### ISSUE THREAD

**Issue by mygizli04** [Minehut/MinehutBOT#69]
There is no `minehut.js` or `config-example.json` anywhere in this repo, and none are linked.

**Comment by Sniped** [comment]
I'll be making a PR with a more updated README soon, just need to rebase my master branch which all of my changes in https://github.com/Minehut/MinehutBOT/pull/59.

**Comment by jellz** [comment]
Try [these instructions](https://github.com/Sniped/MinehutBOT/blob/9c590564e47e9a812d221b1149157312d7d9f3fc/README.md#usage)

**Comment by mygizli04** [comment]
Where do i set the Bot token?

**Comment by MiginsMC** [comment]
In the .env
```
MONGO_URI=mongodb://localhost/minehutbot
DISCORD_TOKEN=
DISCORD_PREFIX=!
OWNER_IDS=
SENTRY_DSN=
NODE_ENV=production

EMOJI_CROSS=
EMOJI_CHECK=
EMOJI_WARNING=
EMOJI_AHH=
EMOJI_LOADING=
EMOJI_DAB=
EMOJI_STATUS_ONLINE=
EMOJI_STATUS_DND=
``` 
(from jellz's [.env.example](https://github.com/jellz/MinehutBOT/blob/master/.env.example))

**Comment by Sniped** [comment]
While very much late, this is resolved with https://github.com/Minehut/MinehutBOT/pull/129.
